-- V26: Replace fake seed jobs with real Summer 2026 SWE & AI internship roles
-- Source: Pitt CSC & Simplify Summer2026-Internships (https://github.com/SimplifyJobs/Summer2026-Internships)

-- ─── 1. Wipe existing fake data ──────────────────────────────────────────────
DELETE FROM saved_jobs;
DELETE FROM jobs;
DELETE FROM companies;

-- ─── 2. Insert real companies ─────────────────────────────────────────────────
INSERT INTO companies (name, industry, logo_url, description)
VALUES
  ('Togetherwork',                     'Software',               'https://logo.clearbit.com/togetherwork.com',             'Community & event management software'),
  ('Mark43',                           'Public Safety Tech',     'https://logo.clearbit.com/mark43.com',                   'Modern software for public safety agencies'),
  ('Vendelux',                         'Event Intelligence',     'https://logo.clearbit.com/vendelux.com',                 'AI-powered event intelligence platform'),
  ('AssetWorks',                       'Asset Management',       'https://logo.clearbit.com/assetworks.com',               'Fleet and asset management solutions'),
  ('KLA Corporation',                  'Semiconductor',          'https://logo.clearbit.com/kla.com',                      'Process control equipment for semiconductors'),
  ('First American',                   'Financial Services',     'https://logo.clearbit.com/firstam.com',                  'Title insurance and real estate services'),
  ('Uber',                             'Transportation Tech',    'https://logo.clearbit.com/uber.com',                     'Global ride-sharing and delivery platform'),
  ('Arcadis',                          'Engineering',            'https://logo.clearbit.com/arcadis.com',                  'Design and consultancy for natural and built assets'),
  ('Emerson Electric',                 'Industrial Technology',  'https://logo.clearbit.com/emerson.com',                  'Automation solutions and industrial technology'),
  ('Fiserv',                           'Fintech',                'https://logo.clearbit.com/fiserv.com',                   'Financial services technology company'),
  ('Veeva Systems',                    'Life Sciences Tech',     'https://logo.clearbit.com/veeva.com',                    'Cloud-based software for life sciences'),
  ('Signify',                          'Lighting Technology',    'https://logo.clearbit.com/signify.com',                  'World leader in lighting products and systems'),
  ('TikTok',                           'Social Media',           'https://logo.clearbit.com/tiktok.com',                   'Global short-form video platform'),
  ('Poshmark',                         'E-Commerce',             'https://logo.clearbit.com/poshmark.com',                 'Social commerce marketplace for fashion'),
  ('General Dynamics Mission Systems', 'Defense & Aerospace',    'https://logo.clearbit.com/gdmissionsystems.com',         'Advanced mission-critical systems'),
  ('ChargePoint',                      'Clean Energy',           'https://logo.clearbit.com/chargepoint.com',              'EV charging network and solutions'),
  ('ABC Fitness',                      'Fitness Tech',           'https://logo.clearbit.com/abcfitness.com',               'Software solutions for the fitness industry'),
  ('Tencent',                          'Technology',             'https://logo.clearbit.com/tencent.com',                  'Global technology and entertainment company'),
  ('Uhaul',                            'Transportation',         'https://logo.clearbit.com/uhaul.com',                    'Moving and storage solutions'),
  ('Northspyre',                       'Real Estate Tech',       'https://logo.clearbit.com/northspyre.com',               'Intelligence platform for real estate developers'),
  ('Five9',                            'Cloud Contact Center',   'https://logo.clearbit.com/five9.com',                    'Cloud contact center and AI solutions'),
  ('HPR',                              'Financial Technology',   'https://logo.clearbit.com/hyannisportresearch.com',      'High-frequency trading and research firm'),
  ('Leidos',                           'Defense & IT',           'https://logo.clearbit.com/leidos.com',                   'Defense, intelligence, and health technologies'),
  ('Western Union',                    'Fintech',                'https://logo.clearbit.com/westernunion.com',             'Global cross-border money movement'),
  ('Revvity',                          'Life Sciences',          'https://logo.clearbit.com/revvity.com',                  'Life sciences tools and diagnostics'),
  ('Zoox',                             'Autonomous Vehicles',    'https://logo.clearbit.com/zoox.com',                     'Autonomous vehicle company by Amazon'),
  ('Ripple',                           'Blockchain / Fintech',   'https://logo.clearbit.com/ripple.com',                   'Blockchain-based payment solutions'),
  ('Trumid',                           'Fintech',                'https://logo.clearbit.com/trumid.com',                   'Electronic bond trading platform'),
  ('Kognitos',                         'AI Automation',          'https://logo.clearbit.com/kognitos.com',                 'Business process automation with AI'),
  ('Very Good Security',               'Cybersecurity',          'https://logo.clearbit.com/verygoodsecurity.com',         'Data security and tokenization platform'),
  ('RTX',                              'Aerospace & Defense',    'https://logo.clearbit.com/rtx.com',                     'Raytheon Technologies aerospace systems'),
  ('Canon',                            'Technology',             'https://logo.clearbit.com/canon.com',                   'Imaging and optical products'),
  ('Axos Bank',                        'Banking',                'https://logo.clearbit.com/axosbank.com',                 'Digital bank and financial services'),
  ('Vanguard',                         'Investment Management',  'https://logo.clearbit.com/vanguard.com',                 'Investment management company'),
  ('Equinix',                          'Data Centers',           'https://logo.clearbit.com/equinix.com',                  'Global digital infrastructure company'),
  ('InvoiceCloud',                     'Fintech',                'https://logo.clearbit.com/invoicecloud.com',             'Electronic billing and payment solutions'),
  ('Socure',                           'Identity Verification',  'https://logo.clearbit.com/socure.com',                   'AI-powered digital identity verification'),
  ('SS&C',                             'Financial Services',     'https://logo.clearbit.com/ssctech.com',                  'Financial services software and solutions'),
  ('General Dynamics IT',              'Defense & IT',           'https://logo.clearbit.com/gdit.com',                    'IT solutions for government and defense'),
  ('Nasuni',                           'Cloud Storage',          'https://logo.clearbit.com/nasuni.com',                   'Hybrid cloud storage platform'),
  ('Nio',                              'Electric Vehicles',      'https://logo.clearbit.com/nio.com',                     'Smart electric vehicle company'),
  ('Mariana Minerals',                 'Mining Tech',            'https://logo.clearbit.com/marianaminerals.com',          'Technology for mineral exploration'),
  ('LivaNova',                         'Medical Technology',     'https://logo.clearbit.com/livanova.com',                 'Medical devices for cardiac and neuro'),
  ('Appian',                           'Low-Code Platform',      'https://logo.clearbit.com/appian.com',                   'Low-code automation platform'),
  ('Tenstorrent',                      'AI Hardware',            'https://logo.clearbit.com/tenstorrent.com',              'AI compute hardware company'),
  ('Zscaler',                          'Cybersecurity',          'https://logo.clearbit.com/zscaler.com',                  'Cloud-native security platform'),
  ('Efficient Computer',               'AI Hardware',            'https://logo.clearbit.com/efficientcomputer.com',        'Energy-efficient AI chip startup'),
  ('SumUp',                            'Fintech',                'https://logo.clearbit.com/sumup.com',                    'Mobile point-of-sale solutions'),
  ('Parsons',                          'Defense & Engineering',  'https://logo.clearbit.com/parsons.com',                  'Technology-focused defense & infrastructure'),
  ('Magna',                            'Automotive Tech',        'https://logo.clearbit.com/magna.com',                   'Automotive technology and manufacturing'),
  ('The Joint Commission',             'Healthcare',             'https://logo.clearbit.com/jointcommission.org',          'Healthcare organization accreditation'),
  ('Dover',                            'Diversified Manufacturing','https://logo.clearbit.com/dovercorporation.com',       'Diversified global manufacturer'),
  ('The New York Times',               'Media & Technology',     'https://logo.clearbit.com/nytimes.com',                  'Leading digital news platform'),
  ('Rocket Lawyer',                    'Legal Tech',             'https://logo.clearbit.com/rocketlawyer.com',             'Online legal services platform'),
  ('Hootsuite',                        'Social Media Tech',      'https://logo.clearbit.com/hootsuite.com',                'Social media management platform'),
  ('Generac',                          'Energy Technology',      'https://logo.clearbit.com/generac.com',                  'Power generation and energy solutions'),
  ('Point72',                          'Hedge Fund',             'https://logo.clearbit.com/point72.com',                  'Global asset management firm'),
  ('Baird',                            'Financial Services',     'https://logo.clearbit.com/rwbaird.com',                  'Employee-owned financial services firm'),
  ('Uline',                            'Distribution',           'https://logo.clearbit.com/uline.com',                   'Industrial packaging and supply distribution'),
  ('Toshiba Global Commerce',          'Retail Technology',      'https://logo.clearbit.com/toshibagcs.com',               'Point-of-sale and retail tech solutions'),
  ('Onto Innovation',                  'Semiconductor',          'https://logo.clearbit.com/ontoinnovation.com',           'Process control for semiconductor manufacturing'),
  ('Cadence Design Systems',           'EDA Software',           'https://logo.clearbit.com/cadence.com',                  'Electronic design automation tools'),
  ('Tradeweb',                         'Financial Markets',      'https://logo.clearbit.com/tradeweb.com',                 'Electronic trading platforms for fixed income'),
  ('Firemon',                          'Cybersecurity',          'https://logo.clearbit.com/firemon.com',                  'Network security policy management'),
  ('Amazon',                           'E-commerce & Cloud',     'https://logo.clearbit.com/amazon.com',                   'Global e-commerce and cloud computing'),
  ('Cloudflare',                       'Internet Security',      'https://logo.clearbit.com/cloudflare.com',               'Web performance and security company'),
  ('EarnIn',                           'Fintech',                'https://logo.clearbit.com/earnin.com',                   'Earned wage access financial app'),
  ('Zendesk',                          'CRM & Support',          'https://logo.clearbit.com/zendesk.com',                  'Customer service software platform'),
  ('CACI',                             'Defense & IT',           'https://logo.clearbit.com/caci.com',                    'IT and professional services for defense'),
  ('Tessera Labs',                     'Deep Tech',              'https://logo.clearbit.com/tessera-labs.com',             'Deep technology startup'),
  ('Attentive',                        'Marketing Tech',         'https://logo.clearbit.com/attentive.com',                'AI-powered conversational commerce platform'),
  ('Anduril',                          'Defense Tech',           'https://logo.clearbit.com/anduril.com',                  'Defense technology and autonomous systems'),
  ('BigCommerce',                      'E-Commerce Platform',    'https://logo.clearbit.com/bigcommerce.com',              'Open SaaS e-commerce platform'),
  ('Eulerity',                         'Marketing Tech',         'https://logo.clearbit.com/eulerity.com',                 'AI-powered marketing automation'),
  ('Fortive',                          'Industrial Technology',  'https://logo.clearbit.com/fortive.com',                  'Intelligent operating and workflow solutions'),
  ('Actian',                           'Data Management',        'https://logo.clearbit.com/actian.com',                   'Hybrid cloud data management'),
  ('SiFive',                           'Semiconductor',          'https://logo.clearbit.com/sifive.com',                   'RISC-V processor design company'),
  ('IXL Learning',                     'EdTech',                 'https://logo.clearbit.com/ixl.com',                     'Personalized learning platform'),
  ('State Street',                     'Financial Services',     'https://logo.clearbit.com/statestreet.com',              'Global custodian and asset manager'),
  ('Fidelity Investments',             'Financial Services',     'https://logo.clearbit.com/fidelity.com',                 'Investment management and brokerage'),
  ('Rackner',                          'Cloud Consulting',       'https://logo.clearbit.com/rackner.com',                  'Cloud-native consulting for government'),
  ('Intapp',                           'Professional Services Tech','https://logo.clearbit.com/intapp.com',                'Software for professional services firms'),
  ('WSP',                              'Engineering Consulting',  'https://logo.clearbit.com/wsp.com',                    'Global engineering and professional services'),
  ('Aledade',                          'Healthcare Tech',        'https://logo.clearbit.com/aledade.com',                  'Value-based care for primary care practices'),
  ('AllTrails',                        'Outdoor Tech',           'https://logo.clearbit.com/alltrails.com',                'Hiking and trail discovery platform'),
  ('Whatnot',                          'Live Commerce',          'https://logo.clearbit.com/whatnot.com',                  'Live shopping and collectibles marketplace'),
  ('Trane Technologies',               'Climate Control',        'https://logo.clearbit.com/tranetechnologies.com',        'Climate innovation for buildings and transport'),
  ('Tandem Diabetes Care',             'Medical Tech',           'https://logo.clearbit.com/tandemdiabetes.com',           'Insulin delivery systems and digital health'),
  ('Snyk',                             'Developer Security',     'https://logo.clearbit.com/snyk.io',                     'Developer-first security platform'),
  ('BillionToOne',                     'Genomics',               'https://logo.clearbit.com/billiontoone.com',             'Next-generation diagnostic tests'),
  ('Haize Labs',                       'AI Safety',              'https://logo.clearbit.com/haizelabs.com',                'AI safety and red-teaming research'),
  ('Strata Decision Technology',       'Healthcare Finance',     'https://logo.clearbit.com/stratadecision.com',           'Financial planning for health systems'),
  ('Octopus Energy',                   'Clean Energy',           'https://logo.clearbit.com/octopus.energy',               'Renewable energy and tech company'),
  ('Baker Hughes',                     'Energy Technology',      'https://logo.clearbit.com/bakerhughes.com',              'Energy technology company'),
  ('Space Dynamics Laboratory',        'Aerospace & Defense',    'https://logo.clearbit.com/spacedynamicslaboratory.com',  'Space science and systems development'),
  ('Fortinet',                         'Cybersecurity',          'https://logo.clearbit.com/fortinet.com',                 'Network security and firewall solutions'),
  ('KION Group',                       'Industrial Tech',        'https://logo.clearbit.com/kiongroup.com',                'Warehouse automation and material handling'),
  ('Ryder System',                     'Logistics',              'https://logo.clearbit.com/ryder.com',                   'Supply chain and fleet management'),
  ('Westinghouse Electric',            'Nuclear Energy',         'https://logo.clearbit.com/westinghousenuclear.com',      'Nuclear energy systems and services'),
  ('Scientific Research Corporation',  'Defense R&D',            'https://logo.clearbit.com/scires.com',                  'Advanced technology for defense and intelligence')
ON CONFLICT (name) DO NOTHING;

-- ─── 3. Insert real SWE & AI internship roles ────────────────────────────────
INSERT INTO jobs (company_id, title, location, job_type, salary, description, requirements, posted_at, apply_url, featured_order)
SELECT c.id, j.title, j.location, j.job_type, j.salary, j.description, j.requirements, now() - j.posted_offset, j.apply_url, j.ord
FROM (VALUES
  -- 0 days ago
  ('Togetherwork',                     'AI Engineering Intern',                                    'Austin, TX',              'Internship', 'Competitive', 'Build AI engineering solutions for community and event management software at Togetherwork.', 'Python,AI,Machine Learning,APIs', INTERVAL '1 hour',  'https://togetherwork.com/application/?gh_jid=8515267002', 1),
  ('Mark43',                           'Mobile Engineer Intern',                                   'Boston, MA',              'Internship', 'Competitive', 'Develop mobile applications for public safety agencies at Mark43.', 'Swift,iOS,Android,Kotlin,Mobile Development', INTERVAL '2 hours',  'https://mark43.com/list-job/7819132?gh_jid=7819132', 2),
  ('Vendelux',                         'Product Engineering Intern',                               'New York, NY',            'Internship', 'Competitive', 'Build product engineering features for an AI-powered event intelligence platform.', 'React,TypeScript,Node.js,Product Engineering', INTERVAL '3 hours',  'https://jobs.ashbyhq.com/vendelux/58bd403e-6ad2-4f85-8d0f-db9ee33f068a/application', 3),
  ('AssetWorks',                       'Software Engineer Intern',                                 'Villanova, PA',           'Internship', 'Competitive', 'Develop software solutions for fleet and asset management systems.', 'Java,SQL,Spring Boot,Software Engineering', INTERVAL '4 hours',  'https://volarisgroup.wd3.myworkdayjobs.com/AssetWorks/job/United-States---Wayne-PA/Software-Engineer-Intern_R66512', 4),
  ('KLA Corporation',                  'Software Engineering Intern',                              'Milpitas, CA',            'Internship', 'Competitive', 'Work on process control software for semiconductor manufacturing equipment.', 'C++,Python,Software Engineering,Algorithms', INTERVAL '5 hours',  'https://kla.wd1.myworkdayjobs.com/search/job/Milpitas-CA/Software-Engineering-Intern_2532227-1', 5),
  ('First American',                   'AI Undergraduate Intern',                                  'Orange, CA',              'Internship', 'Competitive', 'Apply AI and machine learning techniques to real estate and title insurance workflows.', 'Python,Machine Learning,AI,Data Science', INTERVAL '6 hours',  'https://firstam.wd1.myworkdayjobs.com/firstamericancareers/job/USA-California-Santa-Ana/AI-Undergraduate-Internship_R056023', 6),
  ('Uber',                             'Software Engineer Intern',                                 'Sunnyvale, CA',           'Internship', 'Competitive', 'Build and scale engineering systems powering billions of trips at Uber.', 'Python,Go,Java,Distributed Systems,Algorithms', INTERVAL '7 hours',  'https://www.uber.com/global/en/careers/list/158579/', 7),
  ('Arcadis',                          'Developer Intern - Portfolio Insights',                    'Houston, TX',             'Internship', 'Competitive', 'Develop portfolio analytics and insight tools for infrastructure projects.', 'Python,SQL,Data Visualization,REST APIs', INTERVAL '8 hours',  'https://ebcs.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/39922', 8),
  ('Emerson Electric',                 'Software Engineering Intern',                              'Austin, TX',              'Internship', 'Competitive', 'Design and build automation software for industrial control systems at Emerson.', 'C++,Python,Embedded Systems,Software Engineering', INTERVAL '9 hours',  'https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/26004081', 9),
  ('Fiserv',                           'Application Development Intern',                           'Alpharetta, GA',          'Internship', 'Competitive', 'Build financial services applications powering millions of transactions daily.', 'Java,Spring Boot,SQL,APIs,Microservices', INTERVAL '10 hours', 'https://fiserv.wd5.myworkdayjobs.com/ext/job/Alpharetta-Georgia/Application-Development--Summer-Intern_R-10390264', 10),
  ('TikTok',                           'Software Engineer Intern - Recommendation Infrastructure','San Jose, CA',            'Internship', 'Competitive', 'Build large-scale recommendation infrastructure serving billions of users on TikTok.', 'C++,Python,Distributed Systems,Recommendation Systems,Backend', INTERVAL '11 hours', 'https://lifeattiktok.com/search/7629500062003218741', 11),
  ('Veeva Systems',                    'Software Engineer in Test Intern',                         'Toronto, ON, Canada',     'Internship', 'Competitive', 'Build automated test frameworks for cloud software in the life sciences industry.', 'Java,Python,Test Automation,Selenium,QA', INTERVAL '12 hours', 'https://jobs.lever.co/veeva/02b4428c-240e-456a-80d2-59ef8e6a013c/apply', 12),

  -- 1 day ago
  ('Space Dynamics Laboratory',        'Software Engineer Intern',                                 'Ogden, UT',               'Internship', 'Competitive', 'Develop software for space science missions and advanced defense systems.', 'C++,Python,Embedded Systems,Space Systems', INTERVAL '1 day',   'https://spacedynamicslaboratory.applytojob.com/apply/wdcyiwF6Sv/Software-Engineer-Intern', 13),
  ('Poshmark',                         'Cloud Platform Engineer Intern',                           'Redwood City, CA',        'Internship', 'Competitive', 'Build and maintain cloud platform infrastructure for a leading social commerce marketplace.', 'AWS,Kubernetes,Terraform,Cloud Infrastructure,DevOps', INTERVAL '1 day',   'https://jobs.ashbyhq.com/poshmark/062b84e6-1633-43ae-870b-83cb62893caa', 14),
  ('General Dynamics Mission Systems', 'Software Engineer Intern',                                 'Pittsburgh, PA',          'Internship', 'Competitive', 'Develop mission-critical software systems for defense applications.', 'C++,Java,Embedded Systems,Real-Time Systems', INTERVAL '1 day',   'https://careers-gdms.icims.com/jobs/72142/job', 15),
  ('ChargePoint',                      'Software QA Engineering Intern',                           'Campbell, CA',            'Internship', 'Competitive', 'Ensure quality of EV charging software through automated and manual testing.', 'Python,Selenium,Test Automation,QA,REST APIs', INTERVAL '1 day',   'https://www.chargepoint.com/about/opportunities/software-qa-engineering-intern?gh_jid=8505201002', 16),

  -- 2 days ago
  ('ABC Fitness',                      'Software Engineer Intern',                                 'Frisco, TX',              'Internship', 'Competitive', 'Build software solutions for fitness businesses and gym management platforms.', 'Java,React,SQL,Spring Boot,REST APIs', INTERVAL '2 days',  'https://abcfinancial.wd5.myworkdayjobs.com/abcfinancialservices/job/Dallas-TX/Software-Engineer---Intern_REQ-1246', 17),
  ('Tencent',                          'Software Engineering Intern - Backend Development',        'London, UK',              'Internship', 'Competitive', 'Build scalable backend services for global gaming and entertainment products at Tencent.', 'Java,Python,Go,Distributed Systems,Microservices,Backend', INTERVAL '2 days',  'https://tencent.wd1.myworkdayjobs.com/OA_Huoshui_Platform/job/UK-London/Software-Engineering-Intern--Backend-Development_R107174', 18),
  ('Tencent',                          'Software Engineering Intern - PC Game Client',             'London, UK',              'Internship', 'Competitive', 'Develop PC game client software for world-class gaming titles at Tencent.', 'C++,Game Development,Graphics,Unreal Engine,Software Engineering', INTERVAL '2 days',  'https://tencent.wd1.myworkdayjobs.com/OA_Huoshui_Platform/job/UK-London/Software-Engineering-Intern_R107162', 19),

  -- 3 days ago
  ('Uhaul',                            'Software Development Intern',                              'Phoenix, AZ',             'Internship', 'Competitive', 'Build internal software tools and customer-facing features for a large moving and storage company.', 'Java,React,SQL,Agile,Software Development', INTERVAL '3 days',  'https://uhaul.wd1.myworkdayjobs.com/UhaulJobs/job/Phoenix-Arizona/Software-Development-Summer-Intern_R242785', 20),
  ('Northspyre',                       'AI Engineer Intern',                                       'Atlanta, GA',             'Internship', 'Competitive', 'Build AI features for a real estate development intelligence platform.', 'Python,LLMs,Machine Learning,OpenAI,AI Engineering', INTERVAL '3 days',  'https://job-boards.greenhouse.io/northspyre/jobs/7704668003', 21),
  ('Five9',                            'Software Developer AI Insights Intern',                    'San Ramon, CA',           'Internship', 'Competitive', 'Develop AI-powered analytics and insights for cloud contact center solutions.', 'Python,Machine Learning,NLP,AI,Data Analytics', INTERVAL '3 days',  'https://www.five9.com/about/careers/job-detail?gh_jid=5973615004', 22),
  ('HPR',                              'Software Engineering Intern',                              'Needham, MA',             'Internship', 'Competitive', 'Build low-latency financial software systems for a high-frequency trading firm.', 'C++,Python,Algorithms,Low Latency,Systems Programming', INTERVAL '3 days',  'https://job-boards.greenhouse.io/hyannisportresearch/jobs/6667961003', 23),
  ('Leidos',                           'Software Engineering Intern',                              'Remote',                  'Internship', 'Competitive', 'Develop software solutions for defense, intelligence, and health technology programs.', 'Java,Python,Cloud,Agile,Software Engineering', INTERVAL '3 days',  'https://leidos.wd5.myworkdayjobs.com/External/job/6314-RemoteTeleworker-US/Software-Engineering-Intern_R-00181087', 24),
  ('Western Union',                    'Software Engineer Intern',                                 'Denver, CO',              'Internship', 'Competitive', 'Build scalable financial software powering global cross-border money movement.', 'Java,Spring Boot,Microservices,REST APIs,SQL', INTERVAL '3 days',  'https://westernunion.wd5.myworkdayjobs.com/en-US/WesternUnionJobs/job/Denver---WU-HQ/Software-Engineer---Intern_JR0128141-1', 25),
  ('Revvity',                          'Full-Stack AI Developer Intern',                           'Remote',                  'Internship', 'Competitive', 'Build full-stack AI-powered features for life sciences research tools.', 'React,Python,AI,Node.js,Full Stack,Machine Learning', INTERVAL '3 days',  'https://revvity.wd103.myworkdayjobs.com/External/job/CAD-Remote--ON/Full-Stack-AI-Developer-Intern_JR-043504', 26),

  -- 4 days ago
  ('Uhaul',                            'Android Developer Intern',                                 'Phoenix, AZ',             'Internship', 'Competitive', 'Build and maintain Android mobile applications for Uhaul customers and operations.', 'Kotlin,Android,Java,Mobile Development,REST APIs', INTERVAL '4 days',  'https://uhaul.wd1.myworkdayjobs.com/UhaulJobs/job/Phoenix-Arizona/Android-Developer-Intern_R242635', 27),
  ('Uhaul',                            'iOS Developer Intern',                                     'Phoenix, AZ',             'Internship', 'Competitive', 'Build and maintain iOS mobile applications for Uhaul customers and operations.', 'Swift,iOS,UIKit,Xcode,Mobile Development', INTERVAL '4 days',  'https://uhaul.wd1.myworkdayjobs.com/UhaulJobs/job/Phoenix-Arizona/iOS-Developer-Intern_R242642', 28),
  ('Zoox',                             'Software Engineer Intern - Perception Data',               'San Mateo, CA',           'Internship', 'Competitive', 'Build perception data pipelines for autonomous vehicle systems at Zoox.', 'Python,C++,Computer Vision,ML,Autonomous Systems', INTERVAL '4 days',  'https://jobs.lever.co/zoox/15aa4a31-81e0-4f7a-b9d9-5bc64eb2afb8/apply', 29),
  ('Ripple',                           'Software Engineer Intern - GTreasury',                     'Chicago, IL',             'Internship', 'Competitive', 'Build blockchain-based payment and treasury management software at Ripple.', 'JavaScript,TypeScript,React,Node.js,Blockchain', INTERVAL '4 days',  'https://ripple.com/careers/all-jobs/job/7822192?gh_jid=7822192', 30),
  ('Trumid',                           'AI Automation Intern',                                     'New York, NY',            'Internship', 'Competitive', 'Build AI-powered automation tools for electronic bond trading workflows.', 'Python,Machine Learning,NLP,AI,Automation', INTERVAL '4 days',  'https://job-boards.greenhouse.io/trumid/jobs/7703392003', 31),
  ('Kognitos',                         'Software Engineer Intern - AI-Native',                     'San Jose, CA',            'Internship', 'Competitive', 'Build AI-native business process automation features using LLMs and generative AI.', 'Python,LLMs,OpenAI,NLP,AI Engineering,Backend', INTERVAL '4 days',  'https://jobs.ashbyhq.com/Kognitos/a3c5bd4c-f6fb-4eb0-b943-e0e1a1d878c5/application', 32),
  ('Leidos',                           'Software Engineer Intern',                                 'Gaithersburg, MD',        'Internship', 'Competitive', 'Develop software for government intelligence and health technology programs.', 'Java,Python,Cloud,REST APIs,Agile', INTERVAL '4 days',  'https://leidos.wd5.myworkdayjobs.com/External/job/Gaithersburg-MD/Software-Engineer-Intern_R-00180872', 33),
  ('Very Good Security',               'Application Security Intern',                              'Remote',                  'Internship', 'Competitive', 'Build and test security features for a data security and tokenization platform.', 'Python,Cybersecurity,Penetration Testing,Security Engineering', INTERVAL '4 days',  'https://jobs.lever.co/verygoodsecurity/32fe92a6-13d5-4132-b77c-a7a5ed74f38b/apply', 34),
  ('RTX',                              'Software Engineering Intern',                              'San Jose, CA',            'Internship', 'Competitive', 'Develop advanced software systems for aerospace and defense applications at RTX.', 'C++,Python,Embedded Systems,Algorithms,Software Engineering', INTERVAL '4 days',  'https://globalhr.wd5.myworkdayjobs.com/rec_rtx_ext_gateway/job/US-CA-SAN-JOSE-826--200-Holger-Way--BLDG-826-Ast/Software-Engineering-Intern----Summer-2026----Onsite-_01838965', 35),
  ('Canon',                            'Software Intern',                                          'Irvine, CA',              'Internship', 'Competitive', 'Build software for imaging and document management solutions at Canon USA.', 'C++,Java,Python,Algorithms,Software Development', INTERVAL '4 days',  'https://external-canoncareers.icims.com/jobs/34090/job', 36),
  ('Axos Bank',                        'Automation Analyst Intern',                                'San Diego, CA',           'Internship', 'Competitive', 'Build automation tools and RPA workflows for a digital-first banking platform.', 'Python,RPA,Automation,SQL,Test Engineering', INTERVAL '4 days',  'https://axos.wd5.myworkdayjobs.com/Axos/job/HQ---San-Diego-CA/Automation-Analyst-Intern_JR4507', 37),
  ('Vanguard',                         'Technology Intern',                                        'Manchester, UK',          'Internship', 'Competitive', 'Build technology solutions for one of the world''s largest investment management firms.', 'Java,Python,Cloud,Software Engineering,Financial Systems', INTERVAL '4 days',  'https://vanguard.wd5.myworkdayjobs.com/en-US/contractors_restricted/job/Manchester-United-Kingdom/Technology--IST--Internship---Summer-2026_175112-1', 38),

  -- 5 days ago
  ('Equinix',                          'Software Engineering Intern',                              'Dallas, TX',              'Internship', 'Competitive', 'Build software for the world''s largest digital infrastructure and data center company.', 'Python,Java,Cloud,REST APIs,Backend', INTERVAL '5 days',  'https://equinix.wd1.myworkdayjobs.com/External/job/Dallas/Software-Engineering-Intern_JR-160092', 39),
  ('Equinix',                          'Enterprise AI Intern',                                     'San Carlos, CA',          'Internship', 'Competitive', 'Build enterprise AI tools to automate and scale global data center operations.', 'Python,Machine Learning,LLMs,AI Engineering,Data Science', INTERVAL '5 days',  'https://equinix.wd1.myworkdayjobs.com/External/job/Redwood-City/Enterprise-AI-Intern_JR-160096', 40),
  ('InvoiceCloud',                     'Software Engineering Intern',                              'Boston, MA',              'Internship', 'Competitive', 'Build electronic billing and payment solutions for utilities, governments, and insurers.', 'C#,.NET,React,SQL,Software Engineering', INTERVAL '5 days',  'https://invoicecloud.net/careers/open-positions?gh_jid=7702184003', 41),
  ('Socure',                           'Engineering Intern - AI Agents',                           'Remote',                  'Internship', 'Competitive', 'Build AI agents and ML models for digital identity verification workflows.', 'Python,Machine Learning,LLMs,AI Agents,Data Science', INTERVAL '5 days',  'https://jobs.ashbyhq.com/socure/e54f1700-c922-4bcc-a087-45b24717f974/application', 42),
  ('SS&C',                             'Software Engineer Intern',                                 'Waltham, MA',             'Internship', 'Competitive', 'Build financial services software solutions for asset managers and hedge funds.', 'Java,Python,SQL,Financial Systems,Software Engineering', INTERVAL '5 days',  'https://ssctech.wd1.myworkdayjobs.com/ssctechnologies/job/Waltham-MA---10-CityPoint/Software-Engineer-Intern---Co-op_R42466', 43),
  ('General Dynamics IT',              'Software Developer Intern',                                'Annapolis Junction, MD',  'Internship', 'Competitive', 'Develop software solutions for defense and intelligence government programs.', 'Java,Python,C++,Cloud,Software Engineering', INTERVAL '5 days',  'https://gdit.wd5.myworkdayjobs.com/external_career_site/job/USA-MD-Annapolis-Junction/Summer-2026-Software-Developer-Internship_RQ213388-2', 44),
  ('Nasuni',                           'Software Engineering Intern - Python',                     'Marlborough, MA',         'Internship', 'Competitive', 'Build Python-based features for a hybrid cloud storage platform.', 'Python,Cloud Storage,REST APIs,Backend,Distributed Systems', INTERVAL '5 days',  'https://www.nasuni.com/about-us/careers/open-positions/?gh_jid=5142962008', 45),
  ('Parsons',                          'Software Developer Intern',                                'Remote',                  'Internship', 'Competitive', 'Develop software for defense and intelligence programs at Parsons Corporation.', 'Python,Java,Cloud,Agile,Software Development', INTERVAL '5 days',  'https://parsons.wd5.myworkdayjobs.com/en-US/search/job/US---Remote-Any-Location/Software-Developer-Intern---Summer-2026_R179664-1', 46),

  -- 6 days ago
  ('Nio',                              'AI Agent Intern - Semantic Search',                        'San Jose, CA',            'Internship', 'Competitive', 'Build semantic search and AI agent features for a next-generation smart electric vehicle.', 'Python,NLP,Semantic Search,LLMs,AI,Machine Learning', INTERVAL '6 days',  'https://nio.wd3.myworkdayjobs.com/NIO_Careers/job/San-Jose-US/AI-Agent-Intern--Semantic-Search-_R-000148', 47),
  ('Mariana Minerals',                 'Full-Stack Software Engineer Intern',                      'San Francisco, CA',       'Internship', 'Competitive', 'Build full-stack software for technology-driven mineral exploration.', 'React,Node.js,Python,PostgreSQL,Full Stack', INTERVAL '6 days',  'https://jobs.ashbyhq.com/marianaminerals/a8d2878d-bd25-4eff-9957-3925901bc40d/application', 48),
  ('LivaNova',                         'Systems Engineering & AI Workflows Intern',                'Houston, TX',             'Internship', 'Competitive', 'Build AI-driven workflow automation tools for medical device engineering teams.', 'Python,AI,Machine Learning,Systems Engineering,Process Automation', INTERVAL '6 days',  'https://livanova.wd5.myworkdayjobs.com/search/job/Houston-Texas-United-States/Systems-Engineering---AI-Workflows-Intern_JR-14385', 49),
  ('Appian',                           'Software Engineering Intern',                              'McLean, VA',              'Internship', 'Competitive', 'Build features for a leading low-code automation platform used by enterprises worldwide.', 'Java,React,SQL,REST APIs,Software Engineering', INTERVAL '6 days',  'https://job-boards.greenhouse.io/appian/jobs/7727768', 50),
  ('Signify',                          'Software Engineering Intern',                              'Atlanta, GA',             'Internship', 'Competitive', 'Build embedded and connected software for intelligent lighting control systems.', 'Python,C,Embedded Systems,IoT,REST APIs', INTERVAL '6 days',  'https://lighting.wd3.myworkdayjobs.com/jobs-and-careers/job/Atlanta/Software-Engineering-Intern--Cooper-Lighting-Solutions--Summer-2026-_363549-1', 51),

  -- 7 days ago
  ('Tenstorrent',                      'Applied AI Workflow Automation Intern',                    'Austin, TX',              'Internship', 'Competitive', 'Build AI workflow automation tools for next-generation AI compute hardware.', 'Python,Machine Learning,MLOps,AI,CUDA,Deep Learning', INTERVAL '7 days',  'https://job-boards.greenhouse.io/tenstorrentuniversity/jobs/5104002007', 52),
  ('Zscaler',                          'Software Engineer Intern - Software Development',          'San Jose, CA',            'Internship', 'Competitive', 'Build cloud-native security software for the world''s largest security cloud.', 'Java,Python,Go,Cloud,Microservices,Security', INTERVAL '7 days',  'https://job-boards.greenhouse.io/zscaler/jobs/5103680007', 53),
  ('Efficient Computer',               'Compiler Intern',                                          'San Jose, CA',            'Internship', 'Competitive', 'Build compiler toolchains for energy-efficient AI inference chips.', 'C++,LLVM,Compilers,Programming Languages,Computer Architecture', INTERVAL '7 days',  'https://job-boards.greenhouse.io/efficientcomputer/jobs/4218297009', 54),
  ('SumUp',                            'Mobile Engineering Intern - Android/iOS',                  'London, UK',              'Internship', 'Competitive', 'Build mobile payment experiences for small businesses using SumUp''s mPOS platform.', 'Swift,Kotlin,iOS,Android,Mobile Development', INTERVAL '7 days',  'https://sumup.com/careers/positions/8488446002?gh_jid=8488446002', 55),
  ('SumUp',                            'Fullstack Engineering Intern',                             'London, UK',              'Internship', 'Competitive', 'Build full-stack features for SumUp''s merchant-facing products and dashboards.', 'React,TypeScript,Node.js,PostgreSQL,Full Stack', INTERVAL '7 days',  'https://sumup.com/careers/positions/8488447002?gh_jid=8488447002', 56),
  ('Parsons',                          'Space Ops Software Engineer Intern',                       'Colorado Springs, CO',    'Internship', 'Competitive', 'Develop software for space operations and mission systems at Parsons.', 'C++,Python,Space Systems,Real-Time Software,Embedded', INTERVAL '7 days',  'https://parsons.wd5.myworkdayjobs.com/en-US/search/job/US---CO-Colorado-Springs/Space-Ops-Software-Engineer-Intern--Summer-2026-_R179543-1', 57),
  ('Magna',                            'Software Engineering Intern',                              'Lowell, MA',              'Internship', 'Competitive', 'Build automotive software for advanced driver assistance and vehicle systems.', 'C++,Python,Embedded Systems,Automotive Software,RTOS', INTERVAL '7 days',  'https://wd3.myworkdaysite.com/recruiting/magna/Magna/job/Lowell-Massachusetts-US/Software-Engineering-Summer-Intern_R00238234-1', 58),
  ('The Joint Commission',             'Software Development Intern',                              'Lombard, IL',             'Internship', 'Competitive', 'Build software tools for healthcare accreditation and quality improvement programs.', 'C#,.NET,SQL,REST APIs,Software Development', INTERVAL '7 days',  'https://careers-jointcommission.icims.com/jobs/7225/software-development-internship/job', 59),
  ('Dover',                            'Software Engineer Intern',                                 'Austin, TX',              'Internship', 'Competitive', 'Build industrial and commercial software systems for Dover''s diverse portfolio.', 'Python,C#,Java,REST APIs,Software Engineering', INTERVAL '7 days',  'https://careers.dovercorporation.com/job/Austin-Engineer,-Software-Intern-TX-78728/1383322133/', 60),

  -- 8 days ago
  ('The New York Times',               'Full Stack Engineer Intern',                               'New York, NY',            'Internship', 'Competitive', 'Build digital products and experiences reaching millions of readers at the New York Times.', 'React,Node.js,TypeScript,GraphQL,Full Stack', INTERVAL '10 days', 'https://job-boards.greenhouse.io/thenewyorktimes/jobs/4624814005', 61),

  -- 10 days ago
  ('Rocket Lawyer',                    'AI/ML Intern',                                             'San Francisco, CA',       'Internship', 'Competitive', 'Build AI and ML features for online legal services used by millions of people.', 'Python,Machine Learning,NLP,LLMs,AI Engineering', INTERVAL '10 days', 'https://job-boards.greenhouse.io/rocketlawyer/jobs/5185465008', 62),
  ('Hootsuite',                        'Intern - Internal AI Operations',                          'Vancouver, BC, Canada',   'Internship', 'Competitive', 'Build internal AI tooling and automation for social media management operations.', 'Python,AI,LLMs,Automation,Data Engineering', INTERVAL '10 days', 'https://careers.hootsuite.com/job/?gh_jid=7808288', 63),
  ('Generac',                          'IT Intern - Web Development',                              'Waukesha, WI',            'Internship', 'Competitive', 'Build web applications and internal tools for a leading power generation company.', 'React,JavaScript,Node.js,SQL,Web Development', INTERVAL '10 days', 'https://generac.wd5.myworkdayjobs.com/en-US/external/job/Waukesha-WI---USA/IT-Intern---Web-Development_JR13465', 64),

  -- 11 days ago
  ('General Dynamics Mission Systems', 'Software Engineer Intern',                                 'Scottsdale, AZ',          'Internship', 'Competitive', 'Build embedded and real-time software for defense and intelligence systems.', 'C++,Embedded Systems,Real-Time OS,Java,Defense Software', INTERVAL '11 days', 'https://careers-gdms.icims.com/jobs/71986/job', 65),
  ('Point72',                          'AI Engineer Intern - Long/Short Equities',                 'New York, NY',            'Internship', 'Competitive', 'Build AI-powered tools for quantitative equity investment strategies at Point72.', 'Python,Machine Learning,NLP,Financial Modeling,AI', INTERVAL '11 days', 'https://boards.greenhouse.io/point72/jobs/8500448002', 66),
  ('Baird',                            'Intern - Automation & AI Solutions',                       'Milwaukee, WI',           'Internship', 'Competitive', 'Build automation and AI solutions for a leading employee-owned financial services firm.', 'Python,AI,RPA,Machine Learning,Process Automation', INTERVAL '11 days', 'https://baird.wd1.myworkdayjobs.com/careers/job/WI-Milwaukee/Internship---Automation---AI-Solutions--Milwaukee--WI-_R2026441-1', 67),
  ('Uline',                            'Software Developer Intern',                                'Pleasant Prairie, WI',    'Internship', 'Competitive', 'Build internal ERP and distribution software at one of North America''s top distributors.', 'Java,SQL,C#,Software Development,ERP Systems', INTERVAL '11 days', 'https://uline.wd1.myworkdayjobs.com/en-US/Uline_Careers/job/Pleasant-Prairie-WI/Software-Developer-Internship---Summer-2026_R262813', 68),
  ('Toshiba Global Commerce',          'Agentic Software Engineering Intern',                      'Frisco, TX',              'Internship', 'Competitive', 'Build agentic AI and LLM-powered features for next-generation retail software at Toshiba.', 'Python,LLMs,AI Agents,React,Software Engineering', INTERVAL '11 days', 'https://job-boards.greenhouse.io/toshibaglobalcommercesolutions/jobs/5103766007', 69),
  ('Onto Innovation',                  'Software Engineer Intern',                                 'Stanhope, NJ',            'Internship', 'Competitive', 'Build metrology and process control software for semiconductor manufacturing.', 'C++,Python,C#,Software Engineering,Algorithms', INTERVAL '11 days', 'https://onto.wd1.myworkdayjobs.com/onto_careers/job/Budd-Lake-NJ/Software-Engineer-Internship_R-5711', 70),
  ('Cadence Design Systems',           'Software Engineer Intern',                                 'Boston, MA',              'Internship', 'Competitive', 'Build EDA tools and software used by chip designers worldwide at Cadence.', 'C++,Python,Algorithms,EDA,Software Engineering', INTERVAL '11 days', 'https://cadence.wd1.myworkdayjobs.com/External_Careers/job/BOSTON-02/Software-Engineering-Intern_R52450-1', 71),
  ('Tradeweb',                         'JavaScript UI Developer Intern',                           'London, UK',              'Internship', 'Competitive', 'Build JavaScript and React-based UIs for electronic fixed income trading platforms.', 'JavaScript,React,TypeScript,REST APIs,Frontend', INTERVAL '11 days', 'https://ecnf.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/job/301721', 72),
  ('Firemon',                          'Software Engineering Intern',                              'Kansas City, KS',         'Internship', 'Competitive', 'Build network security policy management software for enterprise customers.', 'Java,Python,React,REST APIs,Cybersecurity', INTERVAL '11 days', 'https://jobs.lever.co/firemon/6071bd55-2b14-4da9-8b67-542f2a025137/apply', 73),
  ('Amazon',                           'Software Development Engineer Intern',                     'Vancouver, BC, Canada',   'Internship', 'Competitive', 'Build systems that power e-commerce and cloud services at global scale at Amazon.', 'Java,Python,AWS,Distributed Systems,Algorithms,Data Structures', INTERVAL '11 days', 'https://amazon.jobs/en/jobs/10387163/software-development-engineer-internship-fall-2026-canada', 74),
  ('Cloudflare',                       'AI Builder Intern',                                        'London, UK',              'Internship', 'Competitive', 'Build AI-powered tools and automation for global customer services at Cloudflare.', 'Python,AI,LLMs,REST APIs,Cloudflare Workers', INTERVAL '11 days', 'https://boards.greenhouse.io/cloudflare/jobs/7736663', 75),

  -- 12 days ago
  ('Cloudflare',                       'Product Marketing Engineer Intern - AI & Automation',     'Austin, TX',              'Internship', 'Competitive', 'Build AI demos, automations, and technical content for Cloudflare''s AI product suite.', 'Python,AI,JavaScript,Cloudflare Workers,LLMs', INTERVAL '12 days', 'https://boards.greenhouse.io/cloudflare/jobs/7781953', 76),
  ('EarnIn',                           'Mobile Engineer Intern - iOS',                             'Mountain View, CA',       'Internship', 'Competitive', 'Build iOS mobile features for a financial app helping workers access earned wages early.', 'Swift,iOS,UIKit,SwiftUI,Mobile Development', INTERVAL '12 days', 'https://job-boards.greenhouse.io/earnin/jobs/7773844', 77),
  ('Zendesk',                          'Software Engineer Intern',                                 'Austin, TX',              'Internship', 'Competitive', 'Build features for customer service software used by thousands of companies worldwide.', 'Ruby,Python,React,REST APIs,Microservices', INTERVAL '12 days', 'https://zendesk.wd1.myworkdayjobs.com/zendesk/job/Austin-Texas-United-States-of-America/Software-Engineer-Intern_R34607', 78),
  ('CACI',                             'Software Engineering Intern',                              'Ypsilanti, MI',           'Internship', 'Competitive', 'Develop software systems for government and defense intelligence programs.', 'C++,Python,Java,Embedded Systems,Defense Software', INTERVAL '12 days', 'https://caci.wd1.myworkdayjobs.com/external/job/US-MI-Ypsilanti/Software-Engineering-Intern---Summer-2026_324253', 79),
  ('Tessera Labs',                     'Software Engineer Intern - Backend',                       'San Jose, CA',            'Internship', 'Competitive', 'Build backend systems for deep technology research and development tools.', 'Python,Go,PostgreSQL,REST APIs,Backend Development', INTERVAL '12 days', 'https://jobs.ashbyhq.com/tessera-labs/dce8d8e5-f169-4bdb-b1c2-f4754fca31e7/application', 80),
  ('KION Group',                       'Software Engineer Intern - Software Execution',            'Grand Rapids, MI',        'Internship', 'Competitive', 'Build warehouse automation and robotics software for supply chain systems.', 'C++,Python,Robotics,Embedded Systems,Software Engineering', INTERVAL '12 days', 'https://kiongroup.wd3.myworkdayjobs.com/en-US/KION_SCS/job/Grand-Rapids-MI-United-States/Software-Engineer-Intern---Software-Execution_JR-0079895', 81),
  ('Ryder System',                     'Integration IT Developer Intern',                          'Miami, FL',               'Internship', 'Competitive', 'Build integration software connecting logistics and fleet management systems.', 'Java,Python,REST APIs,Integration,SQL', INTERVAL '12 days', 'https://ryder.wd5.myworkdayjobs.com/RyderCareers/job/USA---Miami-FL-33178/Integration-IT-Developer-Intern---Remote_R164517', 82),
  ('Fortinet',                         'Software Development Intern',                              'Sunnyvale, CA',           'Internship', 'Competitive', 'Build network security software for one of the world''s largest cybersecurity companies.', 'C,C++,Python,Networking,Cybersecurity,Software Development', INTERVAL '12 days', 'https://edel.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/22609', 83),
  ('Westinghouse Electric',            'Application Development Intern',                           'Grove City, PA',          'Internship', 'Competitive', 'Build enterprise applications for the global nuclear energy industry.', 'C#,.NET,SQL,REST APIs,Application Development', INTERVAL '12 days', 'https://careers.westinghousenuclear.com/job/Cranberry-Township-Application-Development-Intern-Summer-2026-NC/1380751200/', 84),

  -- 13 days ago
  ('Tessera Labs',                     'Software Engineering Intern - Frontend',                   'San Jose, CA',            'Internship', 'Competitive', 'Build frontend interfaces for deep technology research and development platforms.', 'React,TypeScript,JavaScript,CSS,Frontend Development', INTERVAL '13 days', 'https://jobs.ashbyhq.com/tessera-labs/4614d053-2c8f-4317-8cd2-1d1290721b06/application', 85),
  ('Attentive',                        'AI Intern',                                                'New York, NY',            'Internship', 'Competitive', 'Build AI-powered conversational commerce features used by 8,000+ brands.', 'Python,Machine Learning,NLP,LLMs,AI Engineering', INTERVAL '13 days', 'https://job-boards.greenhouse.io/attentive/jobs/4209296009', 86),
  ('Anduril',                          'Software Engineer Intern',                                 'Reston, VA',              'Internship', 'Competitive', 'Build autonomous defense systems and software at one of the fastest-growing defense tech companies.', 'C++,Python,Rust,Distributed Systems,Autonomous Systems', INTERVAL '13 days', 'https://boards.greenhouse.io/andurilindustries/jobs/5071345007', 87),
  ('BigCommerce',                      'Software Engineering Intern - TypeScript/Full Stack',      'Atlanta, GA',             'Internship', 'Competitive', 'Build full-stack e-commerce platform features using TypeScript and React.', 'TypeScript,React,Node.js,GraphQL,Full Stack', INTERVAL '13 days', 'https://bigcommerce.wd12.myworkdayjobs.com/Commerce/job/US---GA---Atlanta-Office/Intern--Software-Engineering---Typescript---Full-Stack_JR102475', 88),
  ('Eulerity',                         'Mobile iOS Developer Intern',                              'New York, NY',            'Internship', 'Competitive', 'Build iOS mobile features for an AI-powered marketing automation platform.', 'Swift,iOS,UIKit,SwiftUI,Mobile Development', INTERVAL '13 days', 'https://job-boards.greenhouse.io/eulerity/jobs/4671025006', 89),
  ('Eulerity',                         'Android Developer Intern',                                 'New York, NY',            'Internship', 'Competitive', 'Build Android mobile features for an AI-powered marketing automation platform.', 'Kotlin,Android,Java,Mobile Development,REST APIs', INTERVAL '13 days', 'https://job-boards.greenhouse.io/eulerity/jobs/4671031006', 90),
  ('Cadence Design Systems',           'Software Intern',                                          'San Jose, CA',            'Internship', 'Competitive', 'Build EDA software and tools that help semiconductor companies design next-gen chips.', 'C++,Python,Algorithms,Software Engineering,EDA Tools', INTERVAL '13 days', 'https://cadence.wd1.myworkdayjobs.com/External_Careers/job/SAN-JOSE/Software-Intern_R54246-1', 91),
  ('Fortive',                          'Software Engineering Intern - AI Enablement',              'Minneapolis, MN',         'Internship', 'Competitive', 'Build AI-enablement features for industrial workflow software at Fortive.', 'Python,AI,Machine Learning,LLMs,Software Engineering', INTERVAL '13 days', 'https://ejta.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/9452', 92),
  ('Fortive',                          'Software Engineering Intern',                              'Kansas City, MO',         'Internship', 'Competitive', 'Build enterprise software for intelligent operating solutions at Fortive.', 'Java,C#,React,SQL,Software Engineering', INTERVAL '13 days', 'https://ejta.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/9437', 93),
  ('Actian',                           'Product Engineer Intern',                                  'Remote',                  'Internship', 'Competitive', 'Build data management and analytics product features for hybrid cloud environments.', 'Python,SQL,REST APIs,Product Engineering,Data Engineering', INTERVAL '13 days', 'https://jobs.lever.co/actian/a28a9ac3-70eb-4c5d-818b-d090b618df78/apply', 94),

  -- 14 days ago
  ('SiFive',                           'Intern - Platform Technology',                             'Austin, TX',              'Internship', 'Competitive', 'Build platform tools and software for RISC-V processor design and simulation.', 'C++,Python,RISC-V,Computer Architecture,Systems Programming', INTERVAL '14 days', 'https://sifive.wd1.myworkdayjobs.com/en-US/sifivecareers/job/Austin-Texas-United-States/Intern---Platform-Technology_R-101065', 95),
  ('Actian',                           'AI Engineer - Database Performance Knowledge',             'Remote',                  'Internship', 'Competitive', 'Build AI models for database performance analysis and query optimization.', 'Python,Machine Learning,SQL,Database Systems,AI Engineering', INTERVAL '14 days', 'https://jobs.lever.co/actian/6638beee-45f5-46ac-9dc1-fbde7f1b5310/apply', 96),
  ('IXL Learning',                     'Software Engineer Intern',                                 'Raleigh, NC',             'Internship', 'Competitive', 'Build adaptive learning software features used by millions of students every day.', 'Java,React,Python,SQL,Software Engineering', INTERVAL '14 days', 'https://www.ixl.com/company/jobs?gh_jid=8486934002', 97),
  ('IXL Learning',                     'Software Engineer Intern',                                 'San Mateo, CA',           'Internship', 'Competitive', 'Build personalized education platform features at IXL''s California headquarters.', 'Java,React,Python,SQL,Software Engineering', INTERVAL '14 days', 'https://www.ixl.com/company/jobs?gh_jid=8486939002', 98),
  ('EarnIn',                           'Software Engineer Intern - Backend',                       'Mountain View, CA',       'Internship', 'Competitive', 'Build backend services powering an earned wage access financial application.', 'Java,Python,Go,Microservices,REST APIs,Backend', INTERVAL '14 days', 'https://job-boards.greenhouse.io/earnin/jobs/7775677', 99),
  ('State Street',                     'Software Engineer Intern',                                 'Burlington, MA',          'Internship', 'Competitive', 'Build financial technology software for one of the world''s largest custodian banks.', 'Java,Python,SQL,Financial Systems,Software Engineering', INTERVAL '14 days', 'https://statestreet.wd1.myworkdayjobs.com/Global/job/Burlington-Massachusetts/Software-Engineer-Intern--6-Month-intern--July--Dec_R-787596', 100),
  ('Fidelity Investments',             'Software Engineer Intern',                                 'Boston, MA',              'Internship', 'Competitive', 'Build investment management and brokerage software serving millions of clients at Fidelity.', 'Java,Python,React,SQL,Microservices', INTERVAL '14 days', 'https://fmr.wd1.myworkdayjobs.com/targeted/job/Boston-MA/Co-op--Software-Engineer_2127396', 101),
  ('Rackner',                          'AI Innovation Fellowship Intern',                          'Hyattsville, MD',         'Internship', 'Competitive', 'Build AI-powered solutions for government and startup clients as part of Rackner''s AI accelerator.', 'Python,AI,LLMs,Cloud,Machine Learning,AWS', INTERVAL '14 days', 'https://job-boards.greenhouse.io/rackner/jobs/4681781005', 102),
  ('Intapp',                           'Software Engineer Intern',                                 'Charlotte, NC',           'Internship', 'Competitive', 'Build cloud software solutions for professional services and financial services firms.', 'C#,.NET,React,SQL,REST APIs', INTERVAL '14 days', 'https://intapp.wd1.myworkdayjobs.com/Intapp/job/Charlotte-NC/Software-Engineer-Intern_R2024898-1', 103),
  ('WSP',                              'Software Developer Intern',                                'Dallas, TX',              'Internship', 'Competitive', 'Build digital engineering tools for global infrastructure and environmental consulting.', 'Python,GIS,REST APIs,SQL,Software Development', INTERVAL '14 days', 'https://emit.fa.ca3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/84271', 104),
  ('Aledade',                          'AI Researcher Intern',                                     'Remote',                  'Internship', 'Competitive', 'Research and build AI models for value-based care and clinical decision support.', 'Python,Machine Learning,NLP,Deep Learning,Research,AI', INTERVAL '14 days', 'https://jobs.lever.co/aledade/c60c9ff9-7011-43a0-802c-d3c3d91b0291/apply', 105),
  ('AllTrails',                        'Android Engineer Intern',                                  'Remote',                  'Internship', 'Competitive', 'Build Android features for the world''s most popular outdoor navigation app.', 'Kotlin,Android,Google Maps,Mobile Development,REST APIs', INTERVAL '14 days', 'https://jobs.lever.co/alltrails/f934fba7-5159-4dab-a6ff-8cbda90579dd', 106),
  ('Whatnot',                          'Software Engineer Intern',                                 'San Francisco, CA',       'Internship', 'Competitive', 'Build live commerce features for a fast-growing collectibles and shopping marketplace.', 'React,Python,Go,GraphQL,Distributed Systems', INTERVAL '14 days', 'https://jobs.ashbyhq.com/whatnot/8250532f-4bfd-4ee5-a041-4a2e54047cf7', 107),

  -- 17 days ago
  ('TikTok',                           'Software Engineer Intern - Model Infrastructure',          'San Jose, CA',            'Internship', 'Competitive', 'Build ML model training and serving infrastructure for TikTok''s AI systems.', 'C++,Python,CUDA,Distributed Systems,Machine Learning,Infrastructure', INTERVAL '17 days', 'https://lifeattiktok.com/search/7624284785283746053', 108),
  ('Trane Technologies',               'Developer Intern',                                         'Winona, MN',              'Internship', 'Competitive', 'Build software for climate control and energy efficiency products at Trane Technologies.', 'C#,Python,Embedded Systems,IoT,Software Development', INTERVAL '17 days', 'https://careers.tranetechnologies.com/global/en/job/92601996', 109),
  ('Actian',                           'Engineering Intern - Pipeline Observability and Lineage',  'Remote',                  'Internship', 'Competitive', 'Build observability and data lineage tools for hybrid cloud data pipelines.', 'Python,SQL,Data Engineering,Observability,REST APIs', INTERVAL '17 days', 'https://jobs.lever.co/actian/dc54b4ff-b83c-48c8-9d9c-169d3d251ef6/apply', 110),
  ('Actian',                           'Software Development Intern - Vector AI',                  'Remote',                  'Internship', 'Competitive', 'Build vector search and AI capabilities for a hybrid cloud data management platform.', 'Python,Vector Databases,AI,Machine Learning,SQL', INTERVAL '17 days', 'https://jobs.lever.co/actian/0e93f417-524a-4137-a3be-5e74d9db75c7/apply', 111),
  ('Actian',                           'AI Engineering Intern',                                    'Remote',                  'Internship', 'Competitive', 'Build AI engineering features for enterprise data management software.', 'Python,AI,Machine Learning,LLMs,Data Engineering', INTERVAL '17 days', 'https://jobs.lever.co/actian/7e55f709-5eb0-472e-bdc4-d89f93b0608f/apply', 112),

  -- 18 days ago
  ('Tandem Diabetes Care',             'AI Solutions Intern',                                      'San Diego, CA',           'Internship', 'Competitive', 'Build AI-powered solutions for insulin delivery and digital health at Tandem Diabetes Care.', 'Python,Machine Learning,AI,Healthcare Data,REST APIs', INTERVAL '18 days', 'https://tandemdiabetes.wd12.myworkdayjobs.com/tandemdiabetes/job/California---High-Bluff/AI-Solutions-Intern_JR100960-2', 113),
  ('Snyk',                             'Software Engineer Intern - Container Security',            'Boston, MA',              'Internship', 'Competitive', 'Build container security scanning features for a leading developer security platform.', 'Go,Python,Docker,Kubernetes,Security Engineering', INTERVAL '18 days', 'https://snyk.wd103.myworkdayjobs.com/External/job/United-States---Boston-Office/Software-Engineer-Intern--Container-_JR100491', 114),

  -- 19 days ago
  ('BillionToOne',                     'AI Engineering Intern',                                    'Menlo Park, CA',          'Internship', 'Competitive', 'Build AI and ML models for next-generation genomic diagnostic testing.', 'Python,Machine Learning,Bioinformatics,AI,Deep Learning', INTERVAL '19 days', 'https://job-boards.greenhouse.io/billiontoone/jobs/4680728005', 115),
  ('Haize Labs',                       'Software Engineer Intern',                                 'New York, NY',            'Internship', 'Competitive', 'Build AI safety and red-teaming research tools to evaluate LLM vulnerabilities.', 'Python,LLMs,AI Safety,Machine Learning,Research Engineering', INTERVAL '19 days', 'https://job-boards.greenhouse.io/haizelabs/jobs/4685944008', 116),
  ('Strata Decision Technology',       'Software Engineer Intern',                                 'Chicago, IL',             'Internship', 'Competitive', 'Build financial planning and analytics software for large health systems.', 'C#,.NET,React,SQL,Software Engineering', INTERVAL '19 days', 'https://job-boards.greenhouse.io/stratacareers/jobs/7685893003', 117),
  ('Octopus Energy',                   'Backend Engineer Intern',                                  'London, UK',              'Internship', 'Competitive', 'Build backend systems for a technology-first renewable energy company.', 'Python,Django,PostgreSQL,REST APIs,Backend Development', INTERVAL '19 days', 'https://jobs.lever.co/octoenergy/763336cc-befe-4df8-882d-f3fff44a9e87/apply', 118),
  ('Scientific Research Corporation',  'Software Engineer Intern',                                 'North Charleston, SC',    'Internship', 'Competitive', 'Build software for advanced defense, intelligence, and maritime systems.', 'C++,Python,Java,Embedded Systems,Defense Software', INTERVAL '19 days', 'https://careers-scires.icims.com/jobs/11082/job', 119),

  -- 20 days ago
  ('Baker Hughes',                     'Software Engineering Intern',                              'Newcastle upon Tyne, UK',  'Internship', 'Competitive', 'Build software for energy technology solutions including sensors, controls, and digital platforms.', 'Python,C++,Embedded Systems,Cloud,IoT', INTERVAL '20 days', 'https://bakerhughes.wd5.myworkdayjobs.com/BakerHughes/job/GB-NU-CRAMLINGTON-ATLEY-WAY-NORTH-NELSON-INDUSTRIAL-ESTATE/XMLNAME-12-month-Emerging-Talent---Software-Intern-2026-Opportunities--Cramlington-_R162706', 120)

) AS j(company_name, title, location, job_type, salary, description, requirements, posted_offset, apply_url, ord)
JOIN companies c ON c.name = j.company_name;
